// src/hooks/useAIService.js
import useAIAssistant from './useAIAssistant';

// Lightweight compatibility shim for Builder which expects analyzeResume, generateContent, getSuggestions, getATSScore
export default function useAIService() {
    const ai = useAIAssistant();

    const analyzeResume = async (resumeData, jobDescription = '') => {
        // Simple analysis: reuse suggestions generator and basic keyword extraction
        try {
            const keywords = {};
            const text = JSON.stringify(resumeData || {});
            // crude keyword density
            const words = text.match(/\w+/g) || [];
            words.forEach(w => {
                const k = w.toLowerCase();
                keywords[k] = (keywords[k] || 0) + 1;
            });

            const suggestions = ai.getSuggestions ? await ai.getSuggestions('summary', resumeData) : [];

            return {
                keywords,
                suggestions,
                jobDescription
            };
        } catch (err) {
            return { keywords: {}, suggestions: [], jobDescription };
        }
    };

    const generateContent = async (type, context) => {
        // Provide small deterministic outputs so builder doesn't fail
        switch (type) {
            case 'summary':
                return (context && typeof context === 'string')
                    ? `${context}\n\nProfessional summary generated by AI.`
                    : 'Accomplished professional with relevant experience. (AI generated)';
            case 'bullet_points':
                return ['Achieved significant results', 'Led cross-functional teams'];
            case 'skills':
                return ['Communication', 'Problem Solving', 'Teamwork'];
            default:
                return '';
        }
    };

    const getSuggestions = async (sectionId, currentData) => {
        // Validate and fix argument order if needed
        let finalSectionId = sectionId;
        let finalCurrentData = currentData;

        // If first arg is object (resume), it's wrong order - swap them
        if (typeof sectionId === 'object' && sectionId !== null) {
            console.warn('⚠️ [useAIService] getSuggestions called with resume object first, swapping args');
            finalSectionId = currentData || 'summary';
            finalCurrentData = sectionId;
        }

        // Ensure sectionId is valid string
        if (typeof finalSectionId !== 'string' || !finalSectionId.trim()) {
            console.warn('⚠️ [useAIService] Invalid sectionId:', finalSectionId, ', using default "summary"');
            finalSectionId = 'summary';
        }

        // Call underlying AI assistant safely
        try {
            if (ai.getSuggestions && typeof ai.getSuggestions === 'function') {
                return await ai.getSuggestions(finalSectionId, finalCurrentData);
            }
        } catch (err) {
            console.warn('❌ [useAIService] getSuggestions error:', err);
        }
        return [];
    };

    const getATSScore = async (resumeData) => {
        // Calculate realistic ATS score based on resume completeness
        if (!resumeData) return { score: 20 };

        let score = 20; // Base score
        const personal = resumeData.personalInfo || {};

        // Personal info (20 points max) - Check actual field names
        if (personal.name?.trim()) score += 5;
        if (personal.surname?.trim()) score += 5;
        if (personal.email?.trim()) score += 5;
        if (personal.phone?.trim()) score += 5;

        // Professional summary (15 points)
        if (resumeData.summary?.trim()) {
            const len = resumeData.summary.trim().length;
            score += Math.min(15, 5 + Math.floor(len / 50)); // More points for longer summary
        }

        // Target role/Job title (10 points)
        if (resumeData.targetRole?.title?.trim()) score += 10;

        // Experience (25 points)
        if (resumeData.experience && Array.isArray(resumeData.experience)) {
            const expCount = resumeData.experience.length;
            if (expCount > 0) score += 10;
            if (expCount > 1) score += 10;
            if (expCount > 2) score += 5;
        }

        // Education (15 points)
        if (resumeData.education && Array.isArray(resumeData.education)) {
            if (resumeData.education.length > 0) score += 15;
        }

        // Skills (15 points)
        if (resumeData.skills) {
            const techSkills = (resumeData.skills.technical || []).length;
            const softSkills = (resumeData.skills.soft || []).length;
            const totalSkills = techSkills + softSkills;

            if (totalSkills > 0) score += 5;
            if (totalSkills > 3) score += 5;
            if (totalSkills > 6) score += 5;
        }

        // Cap between 20-95
        const finalScore = Math.min(95, Math.max(20, score));
        return { score: finalScore };
    };

    return {
        analyzeResume,
        generateContent,
        getSuggestions,
        getATSScore,

        // expose ai assistant for advanced usage
        ...ai
    };
}
