// src/pages/analyzer/AIAnalysisReport.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  FaCheckCircle, FaTimesCircle, FaExclamationCircle, FaChartBar, FaLightbulb,
  FaAward, FaUsers, FaGraduationCap, FaCode, FaTrophy, FaArrowUp, FaDownload
} from 'react-icons/fa';
import toast from 'react-hot-toast';

const AIAnalysisReport = ({ analysis, jobDescription, resumeData }) => {
  const [expandedSection, setExpandedSection] = useState('overview');

  const downloadReport = () => {
    try {
      const reportContent = `
AI RESUME ANALYSIS REPORT
========================

Resume: ${analysis.resumeTitle}
Date: ${new Date(analysis.timestamp).toLocaleDateString()}
Job Title: ${analysis.jobTitle}

OVERALL JOB FIT SCORE: ${analysis.jobFitScore.overallScore}/100 - ${analysis.jobFitScore.recommendation}

===== SKILLS MATCH =====
Match Percentage: ${analysis.skillsMatch.matchPercentage}%

Your Skills: ${analysis.skillsMatch.resumeSkills.join(', ')}

Job Required Skills: ${analysis.skillsMatch.jobSkills.join(', ')}

Matched Skills: ${analysis.skillsMatch.matchedSkills.join(', ')}

Missing Skills: ${analysis.skillsMatch.missingSkills.join(', ')}

===== EXPERIENCE ANALYSIS =====
Total Experience: ${analysis.experienceAnalysis.totalYears} years
Number of Positions: ${analysis.experienceAnalysis.experienceCount}
Summary: ${analysis.experienceAnalysis.summary}

===== ATS SCORE =====
Score: ${analysis.atsScore.score}/${analysis.atsScore.maxScore}
Level: ${analysis.atsScore.level}
Factors:
${analysis.atsScore.factors.map(f => `- ${f}`).join('\n')}

===== RECOMMENDED IMPROVEMENTS =====
${analysis.improvements.map(imp => `
Priority: ${imp.priority.toUpperCase()}
Category: ${imp.category}
Suggestion: ${imp.suggestion}
Impact: ${imp.impact}
`).join('\n')}

===== JOB FIT CRITERIA =====
${analysis.jobFitScore.criteria.map(c => `
${c.met ? '✓' : '✗'} ${c.name}: ${c.value}
`).join('\n')}

Generated by AI Resume Analyzer
`;

      const element = document.createElement('a');
      element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent));
      element.setAttribute('download', `${analysis.resumeTitle}_analysis_${new Date().getTime()}.txt`);
      element.style.display = 'none';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
      
      toast.success('Report downloaded successfully!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download report');
    }
  };

  if (!analysis) {
    return (
      <div className="text-center py-12 bg-gray-50 rounded-lg">
        <p className="text-gray-600">No analysis data available</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg p-6 text-white"
      >
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-3xl font-bold mb-2">{analysis.resumeTitle}</h2>
            <p className="text-blue-100">{analysis.jobTitle}</p>
          </div>
          <button
            onClick={downloadReport}
            className="flex items-center gap-2 bg-white text-blue-600 px-4 py-2 rounded-lg font-semibold hover:bg-blue-50 transition"
          >
            <FaDownload /> Download Report
          </button>
        </div>
      </motion.div>

      {/* Overall Score Card */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white rounded-lg border-2 border-blue-200 p-6 shadow-lg"
      >
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="text-center">
            <div className="text-5xl font-bold text-blue-600 mb-2">
              {analysis.jobFitScore.overallScore}
            </div>
            <div className="text-gray-600 font-semibold">Job Fit Score</div>
            <div className="text-sm text-gray-500 mt-2">
              {analysis.jobFitScore.recommendation}
            </div>
          </div>

          <div className="text-center">
            <div className="text-5xl font-bold text-green-600 mb-2">
              {analysis.skillsMatch.matchPercentage}%
            </div>
            <div className="text-gray-600 font-semibold">Skills Match</div>
            <div className="text-sm text-gray-500 mt-2">
              {analysis.skillsMatch.matchedSkills.length}/{analysis.skillsMatch.jobSkills.length}
            </div>
          </div>

          <div className="text-center">
            <div className="text-5xl font-bold text-purple-600 mb-2">
              {analysis.atsScore.score}
            </div>
            <div className="text-gray-600 font-semibold">ATS Score</div>
            <div className="text-sm text-gray-500 mt-2">
              {analysis.atsScore.level}
            </div>
          </div>

          <div className="text-center">
            <div className="text-5xl font-bold text-orange-600 mb-2">
              {analysis.experienceAnalysis.totalYears}
            </div>
            <div className="text-gray-600 font-semibold">Years Exp.</div>
            <div className="text-sm text-gray-500 mt-2">
              {analysis.experienceAnalysis.experienceCount} positions
            </div>
          </div>
        </div>
      </motion.div>

      {/* Skills Analysis */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="bg-white rounded-lg border border-gray-200 p-6"
      >
        <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaCode className="text-blue-600" /> Skills Analysis
        </h3>
        
        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <h4 className="font-semibold text-gray-700 mb-3">Your Skills</h4>
            <div className="flex flex-wrap gap-2">
              {analysis.skillsMatch.resumeSkills.map((skill, idx) => (
                <span
                  key={idx}
                  className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm font-medium"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>

          <div>
            <h4 className="font-semibold text-gray-700 mb-3">Job Requirements</h4>
            <div className="flex flex-wrap gap-2">
              {analysis.skillsMatch.jobSkills.map((skill, idx) => (
                <span
                  key={idx}
                  className="bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-sm font-medium"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>

          <div className="md:col-span-2">
            <h4 className="font-semibold text-gray-700 mb-3 text-green-600">
              <FaCheckCircle className="inline mr-2" /> Matched Skills
            </h4>
            <div className="flex flex-wrap gap-2">
              {analysis.skillsMatch.matchedSkills.map((skill, idx) => (
                <span
                  key={idx}
                  className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm font-medium"
                >
                  ✓ {skill}
                </span>
              ))}
            </div>
          </div>

          {analysis.skillsMatch.missingSkills.length > 0 && (
            <div className="md:col-span-2">
              <h4 className="font-semibold text-gray-700 mb-3 text-red-600">
                <FaExclamationCircle className="inline mr-2" /> Missing Skills
              </h4>
              <div className="flex flex-wrap gap-2">
                {analysis.skillsMatch.missingSkills.map((skill, idx) => (
                  <span
                    key={idx}
                    className="bg-red-100 text-red-700 px-3 py-1 rounded-full text-sm font-medium"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </motion.div>

      {/* Experience Analysis */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="bg-white rounded-lg border border-gray-200 p-6"
      >
        <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaTrophy className="text-orange-600" /> Experience Summary
        </h3>
        
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-orange-50 to-yellow-50 rounded-lg p-4">
            <div className="text-4xl font-bold text-orange-600 mb-2">
              {analysis.experienceAnalysis.totalYears}+
            </div>
            <div className="text-gray-700 font-semibold">Years of Experience</div>
          </div>

          <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg p-4">
            <div className="text-4xl font-bold text-blue-600 mb-2">
              {analysis.experienceAnalysis.experienceCount}
            </div>
            <div className="text-gray-700 font-semibold">Positions Held</div>
          </div>
        </div>

        <div className="mt-6">
          <h4 className="font-semibold text-gray-700 mb-4">Work History</h4>
          <div className="space-y-3">
            {analysis.experienceAnalysis.roles.map((role, idx) => (
              <div key={idx} className="border-l-4 border-blue-500 pl-4 py-2">
                <div className="font-semibold text-gray-900">{role.title}</div>
                <div className="text-gray-600">{role.company}</div>
                <div className="text-sm text-gray-500">{role.duration}</div>
              </div>
            ))}
          </div>
        </div>
      </motion.div>

      {/* ATS Analysis */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="bg-white rounded-lg border border-gray-200 p-6"
      >
        <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaChartBar className="text-purple-600" /> ATS Compatibility
        </h3>
        
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2">
            <span className="font-semibold text-gray-700">ATS Score</span>
            <span className="text-3xl font-bold text-purple-600">
              {analysis.atsScore.score}/{analysis.atsScore.maxScore}
            </span>
          </div>
          <div className="w-full bg-gray-200 rounded-full h-3">
            <div
              className="bg-gradient-to-r from-purple-500 to-blue-500 h-3 rounded-full transition-all"
              style={{ width: `${(analysis.atsScore.score / analysis.atsScore.maxScore) * 100}%` }}
            />
          </div>
          <div className="text-sm text-gray-600 mt-2">{analysis.atsScore.level}</div>
        </div>

        <div className="space-y-2">
          {analysis.atsScore.factors.map((factor, idx) => (
            <div key={idx} className="flex items-center gap-2 text-gray-700">
              <FaCheckCircle className="text-green-500" />
              <span>{factor}</span>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Improvements */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="bg-white rounded-lg border border-gray-200 p-6"
      >
        <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaLightbulb className="text-yellow-500" /> Recommended Improvements
        </h3>
        
        <div className="space-y-4">
          {analysis.improvements.map((improvement, idx) => (
            <div
              key={idx}
              className={`border-l-4 p-4 rounded ${
                improvement.priority === 'critical'
                  ? 'border-red-500 bg-red-50'
                  : improvement.priority === 'high'
                  ? 'border-orange-500 bg-orange-50'
                  : 'border-yellow-500 bg-yellow-50'
              }`}
            >
              <div className="flex items-start justify-between mb-2">
                <div className="font-semibold text-gray-900">{improvement.category}</div>
                <span
                  className={`text-xs font-bold px-2 py-1 rounded ${
                    improvement.priority === 'critical'
                      ? 'bg-red-200 text-red-700'
                      : improvement.priority === 'high'
                      ? 'bg-orange-200 text-orange-700'
                      : 'bg-yellow-200 text-yellow-700'
                  }`}
                >
                  {improvement.priority.toUpperCase()}
                </span>
              </div>
              <p className="text-gray-700 mb-2">{improvement.suggestion}</p>
              <div className="text-sm text-gray-600 flex items-center gap-2">
                <FaArrowUp className="text-green-500" />
                {improvement.impact}
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Job Fit Criteria */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
        className="bg-white rounded-lg border border-gray-200 p-6"
      >
        <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaAward className="text-blue-600" /> Job Fit Criteria
        </h3>
        
        <div className="space-y-3">
          {analysis.jobFitScore.criteria.map((criterion, idx) => (
            <div
              key={idx}
              className={`flex items-center gap-3 p-3 rounded ${
                criterion.met
                  ? 'bg-green-50 border border-green-200'
                  : 'bg-gray-50 border border-gray-200'
              }`}
            >
              {criterion.met ? (
                <FaCheckCircle className="text-green-600 text-xl" />
              ) : (
                <FaTimesCircle className="text-gray-400 text-xl" />
              )}
              <div className="flex-1">
                <div className="font-semibold text-gray-900">{criterion.name}</div>
                <div className={criterion.met ? 'text-green-700' : 'text-gray-600'}>
                  {criterion.value}
                </div>
              </div>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default AIAnalysisReport;
